### ISSUE TITLE
CHT DATA PIPELINE  Issues with large data sets 

### ISSUE THREAD

**Issue by nomulex** [medic/cht-sync#3] opened 2022-01-26 17:30 UTC
When hosting this we will need to work through how we sync large data sets for both self-hosted and medic hosted projects.  The current suggested options are 
1.  We run the sync during maintenance windows and run large batches to catch up.
2. When we query CouchDB, we run smaller batches so as not to impact performance but be ready to wait for long till all the data is synced.
3. Start from the sequence last reported by couch2pg ( we already have the past data so do we really need to sync it afresh?)
4. Clone the production CouchDB and pull data from that till the pipeline catches up and then point it to production.  
^^ @henokgetachew , @Hareet , @aodhan-domhnaill

**Comment by aodhan-domhnaill** [comment] 2022-01-27 10:10
I don't think it's possible to slow the `_changes` feed down. https://docs.couchdb.org/en/stable/api/database/changes.html.

**Comment by henokgetachew** [comment] 2022-01-27 11:51
@aodhan-domhnaill I was just checking out that link and it seems like `limit` could be used to slow it down?

>limit (number) – Limit number of result rows to the specified value (note that using 0 here has the same effect as 1).

If that works as intended, I think another option (Option No. 5) could be to run sync in small batches during the day and run it without throttle during maintenance windows. Basically a combination of 1 & 2.

**Comment by aodhan-domhnaill** [comment] 2022-01-27 12:52
@henokgetachew It's not polling though. It's running continuous.

**Comment by aodhan-domhnaill** [comment] 2022-01-29 11:52
Another option. We can limit bandwidth on the logstash container.

https://serverfault.com/questions/402994/how-do-i-reserve-bandwidth-for-rsync/403001#403001
https://stackoverflow.com/a/48758203/17071176

**Comment by aodhan-domhnaill** [comment] 2022-01-30 21:09
Also just NGINX can limit download and upload speed. This is probably the easiest. We can just stick a small NGINX container to limit the download speed.

**Comment by nomulex** [comment] 2022-01-31 08:11
I think we need to monitor the container first before we make any conclusions.  The [resource limits](https://kubernetes.io/docs/tasks/configure-pod-container/assign-memory-resource/) that we put should keep the pod in check for starters.

**Comment by witash** [comment] 2024-09-05 08:08
The current version is very different from when this ticket was opened and we are not actively working on optimizing pipeline for large data sets, so we can close this.

**Closed by witash** 2024-09-05 08:08 UTC
