### ISSUE TITLE
cht sync logstash downtime error

### ISSUE THREAD

**Issue by Phil-Mwago** [medic/cht-sync#44] opened 2023-09-22 20:43 UTC
logstash seems to have an error that resolves itself but could have a downtime of over an hour meaning no data is being copied over from couchDB to postgres

**Comment by mrjones-plip** [comment] 2023-09-22 21:21
Thanks for filing the ticket @Phil-Mwago ! Can you post the error message and give some details on how to reproduce the error?

**Comment by Phil-Mwago** [comment] 2023-09-25 09:05
To replicate this, here are the steps:

1. Clone the [cht-sync repo](https://github.com/medic/cht-sync).
2. Navgate into the cht-sync directory and install npm: `npm install`
3. Run this command: `npm run local`

Periodically, I get this error: `Unable to retrieve license information from license server {:message=>"No Available connections"}` and `Attempted to resurrect connection to dead ES instance, but got an error {:url=>"http://elasticsearch:9200/", :exception=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError, :message=>"Elasticsearch Unreachable: [http://elasticsearch:9200/][Manticore::ResolutionFailure] elasticsearch: Name or service not known"}` 
<img width="1497" alt="Screenshot 2023-09-21 at 14 29 49" src="https://github.com/medic/cht-sync/a
<img width="1505" alt="Screenshot 2023-09-21 at 14 31 01" src="https://github.com/medic/cht-sync/assets/41321750/1ab6627d-5811-448e-8026-3a29f727ce64">
ssets/41321750/54390cf7-996e-491e-bd86-54fc41162eb9">
Attached 2 screenshots here.

The error sometimes resolves itself however I noted it took over an hour to resolve thus negates near realtime sync aspect.

**Comment by Phil-Mwago** [comment] 2023-10-17 07:08
Just to add that the error on the generator is a "409 Conflict" error as seen in the data generator. It also always occurs after I suspend the container or restart the machine.
Is this a user identifier issue where the conflict occurs when an the unique document identifier appears on both the generator and couchDB?

![image](https://github.com/medic/cht-sync/assets/41321750/81de50f0-9a91-4591-8fa0-ba84d66098ab)

**Comment by garethbowen** [comment] 2023-10-17 09:46
I think the 409 conflict is because the generator is trying to write docs to couchdb that it has already written. It'd be easy to update the generator to check for this error and ignore it.

**Comment by Phil-Mwago** [comment] 2023-10-31 09:44
@njuguna-n FYI: this is the generator PR.

**Comment by dianabarsan** [comment] 2024-05-20 08:15
It looks like there's nothing to do about this. 
It seems that logstash will try to connect to ElasticSearch to get the license (??) even if ElasticSearch is not even used as an output: https://discuss.elastic.co/t/not-using-elasticsearch-logstash-keeps-asking-for-a-license/322318

And there's no way to turn this off because of TOS.

**Comment by dianabarsan** [comment] 2024-05-20 11:43
These errors should _not_ be causing downtime. 

> I think the 409 conflict is because the generator is trying to write docs to couchdb that it has already written. It'd be easy to update the generator to check for this error and ignore it.

I'm not exactly sure _why_ we would be writing to another CouchDb. 
If this is a local setup, it may be possible that you're using "generated" (this is hardcoded, not generated) CouchDb data, and you're not cleaning up before each run, so you end up reusing the same CouchDb container that already contains the data.

**Comment by andrablaj** [comment] 2024-05-28 14:51
Closing this issue as Logstash will be removed in the [next CHT Sync iteration](https://docs.google.com/document/d/1qqXQ-O9Fimn6UvVQUf5BsOF96caoK1xo0uYZbXzYdSs/edit).

**Closed by andrablaj** 2024-05-28 14:51 UTC
